name: "Build and push workflow image"

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/publish.yml
      - /**/**
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/publish.yml
      - /**/**

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.meta.outputs.tags }}
    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: --debug

      - uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build development image
        uses: docker/build-push-action@v2
        with:
          context: .
          target: ANNOTATION_BUILD_IMAGE
          load: true
          tags: test-image
          pull: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max

      - name: Meta action
        uses: docker/metadata-action@v3
        id: meta
        with:
          images: ghcr.io/${{ github.repository }}
          flavor: latest=${{ github.ref == 'refs/heads/master' }}
          tags: |
            type=ref,event=tag
            type=sha,format=long

      - name: Log in to registry
        uses: docker/login-action@v1
        if: github.event_name == 'push'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push development image
        if: github.event_name == 'push'
        uses: docker/build-push-action@v2
        with:
          context: .
          target: DEPLOY_IMAGE
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
